config/routes.rb
YoFeed::Application.routes.draw do
  devise_for :users

  root 'application#index'
  get '/auth/:provider/callback', to: 'feeds#create'
  resources :feeds do
    resources :stories
  end

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :user
  has_many :stories

  def generate_stories(timemarker)
    parser = ("FeedParser::#{self.provider.titleize}Parser").constantize.new(self)
    parser.parse_feed(timemarker)
  end
  
  def self.find_or_create_with_omniauth(auth)
    obj = find_by_provider_and_uid(auth['provider'], auth['uid'])
    unless obj.present?
      attrs = { uid: auth['uid'],
                provider: auth['provider'],
                name: "#{auth['provider']} feed",
                token: auth['credentials']['token'],
                secret: auth['credentials']['secret'] }
      obj = create(attrs) # and other data you might want from the auth hash
    end
  end

end

app/models/feed_parser/twitter_parser.rb
class FeedParser::TwitterParser
  CONSUMER_KEY = "230VG13eXRiYVbHPrr4Hlg"
  CONSUMER_SECRET = "XYoHWin0z6SaVsRwZyAJaVbqmxOnJ1YPC8RWC3yy6Xc"

  def initialize(context)
    @context = context
  end

  def parse_feed(timemarker)
    client = Twitter::Client.new(
      consumer_key: CONSUMER_KEY,
      consumer_secret: CONSUMER_SECRET,
      oauth_token: @context.token,
      oauth_token_secret: @context.secret
    )
    attrs = {
      count: 20 
    }
    unless timemarker == "0"
      attrs[:since_id] = timemarker.to_i
      attrs[:count] = 100
    end
    tl = client.home_timeline(attrs)
    Rails.logger.ap tl.map(&:to_hash)
    parse_entries(tl)
  end

  private

  def parse_entries(feed)
    feed.map do |entry|
      attrs = {
        author: entry.user.screen_name,
        avatar_url: entry.profile_image_url,
        announce: entry.text,
        time_marker: entry.id
      }
      if entry.media.present?
        attrs[:cover_url] = entry.media.first.media_url
      end
      url = entry.urls.first.expanded_url if entry.urls.present?
      attrs[:url] = url if url
      done_entry = @context.stories.create(attrs)
      TwitterParseWorker.perform_async(done_entry.id) if url
      done_entry
    end
  end
end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :feed
  default_scope { order("time_marker DESC") }

  state_machine :state, initial: :got_from_feed do
    event :full_load do
      transition :got_from_feed => :full_loaded
    end
    after_transition any => :full_loaded do |entry, transition|
      # PrivatePub.publish_to("/stories/updated", entry: {id: entry.id, title: entry.title, cover_url: entry.cover_url})
      Pusher.trigger('stories', 'updated', {id: entry.id, title: entry.title, cover_url: entry.cover_url})
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true

  has_many :feeds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @feeds = current_user.feeds
  end

  def create
    @user = current_user.feeds.find_or_create_with_omniauth(auth_hash)
    redirect_to root_path, notice: "Good!"
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :get_feed

  def index
    last_entry = @feed.stories.first
    tm = last_entry.present? ? last_entry.time_marker : "0"
    @new_count = @feed.generate_stories(tm).count
    logger.ap "New Posts Count: #{@new_count}"
    @stories = @feed.stories
  end

  def show
    @story = @feed.stories.find(params[:id])
  end

  protected

  def get_feed
    @feed = current_user.feeds.find(params[:feed_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/application/index.html.haml
Hello!

app/views/feeds/create.html.haml
%h1 Feeds#create
%p Find me in app/views/feeds/create.html.haml

app/views/feeds/index.html.haml
%h1 Feeds#index
%ul
  - @feeds.each do |feed|
    %li
      = link_to feed.name, feed_stories_path(feed)

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.navbar.navbar-inverse
  .navbar-inner
    .container
      %a.brand YourFeed
      .nav-collapse.collapse
        %ul.nav
          %li
            = link_to 'Home', root_path
          %li
            = link_to 'Feeds', feeds_path
          %li
            - if user_signed_in?
              %a Hi, #{current_user.name}
            - else
              = link_to "Login with Twitter", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
%head
  %title YoFeed
  = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = javascript_include_tag "http://js.pusher.com/2.0/pusher.min.js", "data-turbolinks-track" => true
  = csrf_meta_tags
%body
  .container
    .row
      = render 'layouts/navigation'
    .row
      = render 'layouts/messages'
    .row
      = yield

app/views/stories/index.html.haml
%h1
  = @feed.name
  = "(+#{@new_count})"
%ul.stories.unstyled
  - @stories.each do |story|
    %li.well.span4{id: "story_#{story.id}"}
      %h4= link_to(story.title, feed_story_path(@feed, story)) if story.url.present?
      = image_tag story.cover_url, style: ("display:none" unless story.cover_url.present?)
      %p= story.announce
      %span.label
        = image_tag story.avatar_url, width: 30
        = story.author

app/views/stories/show.html.haml
.well
  %h4= @story.title
  = image_tag @story.cover_url
!= @story.body